export const WINDOW_RESIZED = "WINDOW_RESIZED";
export const SET_SYSTEM_GUUID = "SET_SYSTEM_GUUID";
export const SET_INITIAL_ROUTE = "SET_INITIAL_ROUTE";

// EXPRESS TYPES
const SET_PORT = "SET_PORT";

export default [WINDOW_RESIZED, SET_SYSTEM_GUUID, SET_INITIAL_ROUTE, SET_PORT];
